import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "grid" }}>
        <Link href="/person">person</Link>
        <Link href="/ssr/hydration">hydration</Link>
        <Link href="/ssr/intialData">intialData</Link>
        <Link href="/todo/infinite">infinite</Link>
        <Link href="/test">test</Link>
      </div>
    </div>
  );
};

export default Home;
